GSM-GOGO/GSM-GOGO-Client

- src/components/Timer/index.tsx
- yarn.lock
💡 개요
React hook 에서 권장하는 대문자 함수로 네이밍을 바꿨습니다
🎸 기타
아래 yarn lock은 버전 업그레이드 된 것 같으니 그냥 스쳐지나 가듯이 봐주시면 감사합니다.
> Change FunctionNaming

- src/Pages/Category/Soccer/index.tsx
- src/Pages/Category/Soccer/style.ts
- src/main.tsx
💡 개요
매치 리스트 화면을 퍼블리싱 했습니다. 
📃 작업내용
> [#11] 매치 리스트 화면을 퍼블리싱 했습니다.

- src/Pages/Category/Basketball/index.tsx
- src/Pages/Category/Basketball/style.ts
- src/Pages/Category/Soccer/index.tsx
- src/Pages/Category/Soccer/style.ts
- src/Pages/Category/Volleyball/index.tsx
- src/Pages/Category/Volleyball/style.ts
- src/Pages/Main/index.tsx
- src/Pages/Main/style.ts
- src/components/Category/index.tsx
- src/components/Category/style.ts
💡 개요
체육 대회 분야별 카테고리를 제작하고 각 페이지의 퍼블리싱을 적용했다.
📃 작업내용
- 카테고리 제작
- 카테고리 컴포넌트 변환
- 분야별 컴포넌트 연결
> [#12] 카테고리를 제작 했습니다

- src/App.tsx
- src/Pages/Category/Nomal/index.tsx
- src/Pages/Category/Nomal/style.ts
- src/components/Category/index.tsx
- src/components/Category/style.ts
- src/components/Header/index.tsx
- src/components/Header/style.ts
- src/components/PlayingContainer/index.tsx
💡 개요
컴포넌트들의 변경 사항을 수정 했습니다.
📃 작업내용
- 메인 페이지 모달 제작
- 헤더 변경
- 카테고리 일반경기 추가
🔀 변경사항
> [#14] 컴포넌트들의 변경 사항을 수정 했습니다.

- src/App.tsx
- src/Pages/Category/Basketball/index.tsx
- src/Pages/Category/Basketball/style.ts
- src/Pages/Category/Nomal/index.tsx
- src/Pages/Category/Soccer/index.tsx
- src/Pages/Category/Soccer/style.ts
- src/Pages/Category/Volleyball/index.tsx
- src/Pages/Category/Volleyball/style.ts
- src/Pages/Formation/NomalForm/index.tsx
- src/Pages/Formation/NomalForm/style.ts
- src/assets/svg/OpenReview.tsx
- src/assets/svg/index.ts
- src/components/PlayingContainer/index.tsx
- yarn.lock
💡 개요
일반경기 화면을 퍼블리싱 했습니다 이외 버그를 수정 했습니다
📃 작업내용
- 일반경기 화면 퍼블리싱
- 모달의 버그 수정 
🔀 변경사항
> [#18] 일반경기 화면을 퍼블리싱 했습니다

- src/Pages/Formation/BasketForm/index.tsx
- src/Pages/Formation/SoccerForm/index.tsx
- src/Pages/Formation/VolleyForm/index.tsx
- src/Pages/Formation/VolleyList.tsx
- src/Pages/Formation/style.ts
- src/components/PlayingContainer/style.ts
💡 개요
맡은 퍼블리싱의 console에 출력되는 에러를 해결
📃 작업내용
맡은 퍼블리싱의 console에 출력되는 에러를 해결
🎸 기타
맡지 못한 signin에서 hooks error + signup에서의 이해못한 코드 error 을 해결하지 못하였습니다
> Fix errors

- src/Pages/Formation/NomalForm/index.tsx
- src/Pages/Formation/NomalForm/style.ts
- src/Pages/Ranking/index.tsx
- src/assets/svg/CloseReview.tsx
- src/assets/svg/OpenReview.tsx
- src/assets/svg/index.ts
💡 개요
일반경기 form을 퍼블리싱 했습니다.
📃 작업내용
> [#20] 일반경기 form을 퍼블리싱 했습니다.

- src/Pages/Ranking/index.tsx
- src/Pages/Signup/index.tsx
- src/components/Header/index.tsx
- src/components/Header/style.ts
- src/components/Input/index.tsx
- src/utils/libs/apiClient.ts
💡 개요
- 회원가입 로직 제작
- 로그아웃 로직 제작
📃 작업내용
- 로그아웃 퍼블리싱 모달
- 로그아웃 로직
- 번호 등록 로직
- 인증 코드 로직
> [#27] 회원가입 로직과 로그아웃 로직을 만들었다

- src/components/Header/index.tsx
💡 개요
userPoint 제작
📃 작업내용
userPoint를 제작하였습니다
> Add userPoint

- src/Pages/Register/Badminton/index.tsx
- src/Pages/Register/index.tsx
- src/Pages/Register/nomal.tsx
- src/Pages/Register/style.ts
💡 개요
경기참가 구현 및 Search 를 해야했다
📃 작업내용
🎸 기타
아직 일반경기는 Mockdata입니다
> [#30] 경기참가 구현 및 Search

- src/Pages/Category/Nomal/index.tsx
- src/Pages/Category/Sports/index.tsx
- src/Pages/Formation/BadmintonForm/index.tsx
- src/Pages/Formation/NomalForm/index.tsx
- src/Pages/Formation/SoccerForm/index.tsx
- src/Pages/Formation/VolleyForm/index.tsx
- src/Pages/Main/index.tsx
- src/Pages/Minigame/index.tsx
- src/Pages/Ranking/index.tsx
- src/Pages/Register/Badminton/index.tsx
- src/Pages/Register/Soccer/index.tsx
- src/Pages/Register/Volleyball/index.tsx
- src/Pages/Register/index.tsx
- src/hook/useAccessTokenCheck.tsx
- yarn.lock
💡 개요
access토큰이 없을 때 signin 리다이랙트
📃 작업내용
access토큰이 없을 때 signin으로 리다이랙트 훅 제작
> [#32] access토큰이 없을 때 signin으로 리다이랙트 훅 제작 

- src/Pages/Category/Nomal/style.ts
- src/Pages/Category/Sports/style.ts
- src/Pages/Ranking/index.tsx
- src/Pages/Ranking/style.ts
- src/Pages/Signup/index.tsx
- src/components/Category/style.ts
- src/components/Header/index.tsx
- src/components/Header/style.ts
- src/main.tsx
- src/utils/libs/apiClient.ts
💡 개요
리프래쉬 로직과 일부 페이지 반응형 적용
📃 작업내용
- 리프래쉬의 경우중 403에러외 401에러도 포함
- 페이지 3개 반응형 적용
- 통신 여러번 진행 수정
> [#34] 리프래쉬 로직과 일부 페이지 반응형 적용

- src/components/Header/index.tsx
💡 개요
로그아웃 로직을 제작 했다.
📃 작업내용
-remove 토큰으로 로그아웃로직 제작
> [#36] 로그아웃 로직을 제작 했다.

- src/Pages/Formation/NomalForm/style.ts
> [#39] 일반 경기 폼의 반응형 제작

- src/Pages/Ranking/index.tsx
💡 개요
랭킹을 불러옵니다
📃 작업내용
🎸 기타
태관이의 point동점 처리 부탁해요 ㅎㅎ
> Add RankApi

- src/Pages/Register/nomal.tsx
- src/Pages/Register/style.ts
> [#41] 일반경기 명단 api

- src/Pages/Register/index.tsx
- src/Pages/Register/nomal.tsx
💡 개요
일반경기 제출 버튼에 로직적용을 해야했다
📃 작업내용
🍴 사용방법
개발 테스트 편의를 위해  // disabled={allSportsFull && selectedSport == '일반경기'}
주석처리 된 곳이 있습니다 해당 부분 제거시 모든 경기 유저를 채워야 제출가능합니다
> add logic SubmitButton

- src/Pages/Ranking/index.tsx
- src/Pages/Ranking/style.ts
> add myrank style and responsive

- src/App.tsx
- src/Pages/Category/Nomal/index.tsx
- src/Pages/Category/Nomal/style.ts
- src/Pages/Formation/NomalForm/index.tsx
- src/Pages/Formation/NomalForm/style.ts
- src/Pages/Main/style.ts
- src/Pages/Register/index.tsx
- src/Pages/Signin/index.tsx
- src/Pages/Signup/index.tsx
- src/components/Input/index.tsx
- yarn.lock
> [#43] 잡다한 로직 제작

- src/Pages/Category/Nomal/index.tsx
- src/Pages/Category/Sports/index.tsx
- src/Pages/Formation/BadmintonForm/index.tsx
- src/Pages/Formation/NomalForm/index.tsx
- src/Pages/Formation/SoccerForm/index.tsx
- src/Pages/Formation/VolleyForm/index.tsx
- src/Pages/Main/index.tsx
- src/Pages/Minigame/index.tsx
- src/Pages/Ranking/index.tsx
- src/Pages/Register/Badminton/index.tsx
- src/Pages/Register/Soccer/index.tsx
- src/Pages/Register/Volleyball/index.tsx
- src/Pages/Register/index.tsx
> [#46] 에세스 토큰 유무 로직 수정

- src/Pages/Formation/NomalForm/index.tsx
- src/Pages/Formation/NomalForm/style.ts
- src/Pages/Ranking/index.tsx
- src/Pages/Register/Badminton/index.tsx
- src/Pages/Register/Soccer/index.tsx
- src/Pages/Register/Volleyball/index.tsx
- src/Pages/Register/index.tsx
- src/Pages/Register/nomal.tsx
- src/Pages/Signup/index.tsx
- src/components/Input/index.tsx
💡 개요
빌드 오류를 해결
📃 작업내용
- 랭킹
- 노말폼
> [#47] 빌드 오류 일부 

- src/Pages/Register/nomal.tsx
💡 개요
다른 스포츠 왔다갔다하면 일반경기 스포츠 인원이 초기화 되지 않았다
📃 작업내용
인원이 0으로 초기화 됩니다!
> add resetNormalArr

- src/Pages/Register/style.ts
> registerResponsive

- src/components/Header/style.ts
- src/components/HeaderContainer/style.ts
> [#54] 헤더 & 모달 문제 해결

- src/fonts/woff/PretendardWoff.css
- src/fonts/woff2/PretendardWoff2.css
- src/style/Globalstyles.ts
> add fonts 폰트적용

- src/App.tsx
- src/Pages/Category/Nomal/index.tsx
- src/Pages/Formation/NomalForm/index.tsx
- src/Pages/Register/index.tsx
- src/components/Category/index.tsx
📃 작업내용
/NomalMatch -> /nomal-match
> add NomalMatch restfullApi

- src/Pages/Ranking/index.tsx
- src/Pages/Register/nomal.tsx
💡 개요
랭킹에 동명이인, 누군지 알 수 없어 학년 반 추가
이어달리기 성비 수정
📃 작업내용
> Rank grade class

- src/utils/libs/apiClient.ts
> [#59] 리프래쉬 토큰 재발급 오류 수정

- src/App.tsx
- src/Pages/Ranking/index.tsx
- src/components/Loading/content.tsx
💡 개요
랭킹 요청을 너무 많이 보낸다
📃 작업내용
최초 1회 캐싱 후 5분마다 비교
id비교 api는 최초 1회만
> Rank query

- src/Pages/Category/Nomal/style.ts
- src/Pages/Category/Sports/style.ts
- src/Pages/Formation/BadmintonForm/style.ts
- src/Pages/Formation/SoccerForm/style.ts
- src/Pages/Formation/VolleyForm/style.ts
💡 개요
리스트가 넘치면 addbutton의 위치가 이상해짐
📃 작업내용
fixed로 교체
> add addbutton fixed

- src/App.tsx
- src/hook/useAuthenticate.ts
- src/utils/libs/PrivateRoute.tsx
💡 개요
토큰이 없지만 메인화면이 보이는 버그 수정
📃 작업내용
- Private router 사용
> [#65] 토큰이 없지만 메인화면이 보이는 버그 수정

- src/Pages/Register/Soccer/index.tsx
- src/Pages/Register/index.tsx
- src/components/Header/index.tsx
💡 개요
로그아웃 개선 & 축구 인원 변경
📃 작업내용
- 로그아웃 서버 통신 진행
- 축구 인원 변경
🔀 변경사항
- 로그아웃시 기존에 사용하던 토큰들을 재사용 할 수 없다
- 축구 인원을 9=>8 변경
> [#65] 로그아웃 개선 & 축구 인원 변경

- src/Pages/Formation/NomalForm/index.tsx
- src/Pages/Register/index.tsx
- src/Pages/Register/nomal.tsx
💡 개요
일반게임의 팔자 줄넘기를 추가함
📃 작업내용
- 8자줄넘기 등록
- 조회
> [#67] 일반게임의 팔자 줄넘기를 추가함

- src/App.tsx
- src/Pages/Category/Sports/index.tsx
- src/Pages/Formation/BadmintonForm/index.tsx
- src/Pages/Formation/SoccerForm/index.tsx
- src/Pages/Formation/VolleyForm/index.tsx
💡 개요
포에이션의 url을 params로 변경했다.
📃 작업내용
기존의 useLocation형테에서 params형태로 변경
> [#68] 포에이션의 url을 params로 변경

- src/Pages/Category/Nomal/index.tsx
- src/Pages/Category/Nomal/style.ts
- src/Pages/Category/Sports/index.tsx
- src/Pages/Category/Sports/style.ts
💡 개요
카테고리 스트로크 모바일 화면 수정
📃 작업내용
> [#70] 카테고리 스트로크 모바일 화면 수정

- src/Pages/Formation/BadmintonForm/index.tsx
- src/Pages/Formation/SoccerForm/index.tsx
- src/Pages/Formation/VolleyForm/index.tsx
💡 개요
포메이션 클릭시 왼쪽 위로 순간이동하는 버그 수정
📃 작업내용
포메이션 클릭시 왼쪽 위로 순간이동하는 버그 수정했습니다
> Fix Formation

- src/App.tsx
- src/Pages/Bracket/BadmintonBracket/index.tsx
- src/Pages/Bracket/ScoccerBracket/index.tsx
- src/Pages/Bracket/ScoccerBracket/style.ts
- src/Pages/Bracket/VolleyballBracket/index.tsx
- src/components/MiniGameCategory/index.tsx
- src/components/PlayingContainer/index.tsx
💡 개요
- 선수가 출전한 경기의 로직을 추가 했습니다.
- 대진표 폴더 분할
📃 작업내용
> [#78] 선수가 출전한 경기의 로직을 추가 했습니다. (대진표 폴더 분할)

- index.html
- src/App.tsx
- src/Pages/Bracket/BadmintonBracket/index.tsx
- src/Pages/Bracket/BadmintonBracket/style.ts
- src/Pages/Category/Nomal/index.tsx
- src/Pages/Category/Sports/index.tsx
- src/Pages/Formation/BadmintonForm/index.tsx
- src/Pages/Formation/BadmintonForm/style.ts
- src/Pages/Formation/NomalForm/index.tsx
- src/Pages/Formation/SoccerForm/index.tsx
- src/Pages/Formation/SoccerForm/style.ts
- src/Pages/Formation/VolleyForm/index.tsx
- src/Pages/Formation/VolleyForm/style.ts
- src/Pages/Formation/style.ts
- src/Pages/Minigame/CoinGame/index.tsx
- src/Pages/Minigame/Roulette/index.tsx
- src/Pages/Ranking/style.ts
- src/Pages/Register/index.tsx
- src/Pages/Signup/index.tsx
- src/components/Header/index.tsx
- src/components/Input/index.tsx
- src/components/PlayingContainer/index.tsx
- src/components/PlayingContainer/style.ts
- src/components/WeatherContainer/index.tsx
- src/main.tsx
- src/types/ArrayProps.ts
💡 개요
최신 경기 반영과 응원하는 팀, 팀을 눌렀을때 포메이션이 나오는 작업을 수행하였습니다.
📃 작업내용
최신 경기 반영과 응원하는 팀, 팀을 눌렀을때 포메이션이 나오는 작업을 수행하였습니다.
> feature clickTeamName

- src/components/PlayingContainer/index.tsx
- src/components/PlayingContainer/style.ts
- src/components/PlayingContainer/style1.ts
💡 개요
메인페이지에 디자인이 변경되어 사용자가 투표한 내용을 볼 수 있다
📃 작업내용
🎸 기타
구현되지 않은 부분이 있을 수 있어요
> add main my betting

- src/App.tsx
- src/Pages/MyPage/index.tsx
- src/components/Header/style.ts
- src/components/PlayingContainer/index.tsx
💡 개요
- 마이페이지 필터를 수정했습니다
- 헤더 로고를 디자인에 맞게 수정 했습니다
> [#88] 마이페이지 필터를 수정 했습니다

- src/Pages/Minigame/NunchiGame/index.tsx
> Fix conditionalop

- src/Pages/Bracket/VolleyballBracket/index.tsx
💡 개요
배드민턴 대진표를 업데이트 했습니다
📃 작업내용
> [#96] 배드민턴 대진표를 업데이트 했습니다
